# Generated by Django 2.1.7 on 2019-07-26 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trening', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisesplans',
            name='id',
        ),
        migrations.AlterField(
            model_name='exercisesplans',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Trening.Plans'),
        ),
    ]
