# Generated by Django 2.1.7 on 2019-07-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
