# Generated by Django 2.1.7 on 2019-07-25 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trening', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisesplans',
            old_name='exercises',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='exercisesplans',
            old_name='plans',
            new_name='plan',
        ),
    ]
