# Generated by Django 2.1.7 on 2019-07-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trening', '0002_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/images/image.png', upload_to='media'),
        ),
    ]
