# Generated by Django 2.1.7 on 2019-07-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trening', '0005_auto_20190718_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='static/cl-logo.png', upload_to='profile_pics'),
        ),
    ]
