# Generated by Django 2.1.7 on 2019-07-19 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trening', '0006_auto_20190719_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='User_name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trening.Rating'),
        ),
    ]
