# Generated by Django 2.1.7 on 2019-07-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trening', '0007_auto_20190719_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
