# Generated by Django 2.1.7 on 2019-07-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trening', '0010_auto_20190723_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='sum_of_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Ocena'),
        ),
    ]
