# Generated by Django 2.1.7 on 2019-07-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trening', '0011_auto_20190723_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Ocena'),
        ),
    ]
