# Generated by Django 2.1.7 on 2019-07-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trening', '0012_auto_20190723_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Ocena'),
        ),
    ]
