# Generated by Django 2.1.7 on 2019-07-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trening', '0017_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
